language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=master
  - DJANGO=1.6
  - DJANGO=1.7

install:
  - pip install tox coveralls

script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=master

after_success: coveralls
